feature/sass-header
AnnaYegorova/team-project-group-1 pull request #17
Opened 2021-07-05 14:04 UTC by OlenaZ-nia

Хедер с мобильным меню и JS.

2021-07-05 19:02 UTC, Vladosik12333 requested changes

2021-07-05 19:02 UTC, Vladosik12333 commented on src/sass/layout/_header.scss
> +    // display: inline-block;
Стили закомнчены (может случайно). Почему?

2021-07-05 19:02 UTC, Vladosik12333 commented on src/sass/layout/_header.scss
> +    // display: inline-block;
И там еще четыре ниже, глянь пожалуйста к ним. Удали комменты или используй стили.

2021-07-05 19:21 UTC, OlenaZ-nia commented on src/sass/layout/_header.scss
> +    // display: inline-block;
Я удалю, то уже не нужно

2021-07-05 19:28 UTC, Vladosik12333 commented on src/sass/layout/_header.scss
> +    // display: inline-block;
Жду коммита с правками)

2021-07-05 20:12 UTC, OlenaZ-nia commented on src/sass/layout/_header.scss
> +    // display: inline-block;
Исправила

2021-07-06 07:05 UTC, Vladosik12333 approved these changes

2021-07-06 07:05 UTC, merged