Origin/about/advanced
AnnaYegorova/team-project-group-1 pull request #18
Opened 2021-07-05 14:28 UTC by Ruslan-Tuliabaeiev

about/advanced проверите

2021-07-05 19:24 UTC, Vladosik12333 requested changes

2021-07-05 19:24 UTC, Vladosik12333 commented on src/partials/about.html
> +    <div class="teacher__bloc img">
Нет контейнера

2021-07-05 19:24 UTC, Vladosik12333 commented on src/partials/about.html
> +<div>
Что за див? Может должно быть /div?

2021-07-05 19:24 UTC, Vladosik12333 commented on src/partials/about.html
> +<h2 class="teacher__profesion">
Нет отступов. Код не читаемый.

2021-07-05 19:24 UTC, Vladosik12333 commented on src/partials/about.html
> +        <img class="" src="#" alt="учитель">
Запасной img всегда должен быть самый обычный, на случай, если source не сработают.

2021-07-05 19:24 UTC, Vladosik12333 commented on src/partials/about.html
> +<Ul class="teacher__list list">
ul с большой написан.

2021-07-05 19:24 UTC, Vladosik12333 commented on src/partials/about.html
> +</Ul>
Снова с большой.

2021-07-05 19:24 UTC, Vladosik12333 commented on src/partials/advantages.html
> +<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas, quo.</p>
Это удалить нужно.

2021-07-05 19:24 UTC, Vladosik12333 commented on src/partials/about.html
> +<!-- <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas, quo.</p> -->
Нужно удалить

2021-07-05 19:24 UTC, Vladosik12333 commented on src/partials/advantages.html
> +      <Ul class="">
ul с большой, пустой класс.

2021-07-05 19:24 UTC, Vladosik12333 commented on src/partials/advantages.html
> +    <div class="advantages__bloc">
Нет контейнера.

2021-07-05 19:24 UTC, Vladosik12333 commented on src/sass/layout/_about.scss
> +.list {
Лишнее. Уже есть в бейс.

2021-07-05 19:24 UTC, Vladosik12333 commented on src/sass/layout/_about.scss
> +.link {
Тоже есть в бейс.

2021-07-05 19:24 UTC, Vladosik12333 commented on src/sass/layout/_about.scss
> +line-height: 130%;
Что за проценты?

2021-07-05 19:24 UTC, Vladosik12333 commented on src/sass/layout/_about.scss
> +    fill: black;
Используйте переменные с вариеблис.

2021-07-05 19:24 UTC, Vladosik12333 commented on src/sass/layout/_about.scss
> +    fill: #000;
Используйте переменные с вариеблис.

2021-07-05 19:24 UTC, Vladosik12333 commented on src/sass/layout/_about.scss
> +font-style: normal;
!!!Вместо всех повторяющихся стилей для шрифтов, используйте миксин

2021-07-05 19:24 UTC, Vladosik12333 commented on src/sass/layout/_about.scss
> +color: #111518;
Вроде есть в вариеблис. Если нет - так оставьте.

2021-07-05 19:24 UTC, Vladosik12333 commented on src/sass/layout/_about.scss
> +color: #B9B9B9;
Вроде есть в вариеблис. Если нет - так оставьте.

2021-07-05 19:24 UTC, Vladosik12333 commented on src/sass/layout/_about.scss
> +color: #FF6B09;  // color: var(—accent-colo)
Вроде есть в вариеблис. Если нет - так оставьте.

2021-07-07 10:27 UTC, closed without merging

2021-07-07 10:27 UTC, AnnaYegorova commented
111