add program.html
AnnaYegorova/team-project-group-1 pull request #4
Opened 2021-07-03 20:28 UTC by Vladosik12333

del img for program (В ТЗ указано что картинка в этой секции должна быть загружена через псевдо, собственно картинки не нужны).
add program in html.

2021-07-04 09:04 UTC, OlenaZ-nia commented on src/partials/program.html
> +        <ul>
В ТЗ было написано трехуровневый список. Ты сделал таблицей. Мне кажется была бы проще  разметка  (и как по тз) если:
<ul> и в ней 5 аналогичных лишек (расписую одну что б не слилось все) :
       <li-1>
               <h3>semester</h3>
               <ul>
                       <li-1-1>
                               <h4>grammar</h4>
                                <p> nnnnn </p>
                       </li> 
                        <li-1-2>
                               <h4>vocabulary</h4>
                                <p> lllllll </p>
                       </li> 
                </ul>
        </li>
*цифры только для визуализации

2021-07-04 09:15 UTC, OlenaZ-nia requested changes

2021-07-04 09:15 UTC, OlenaZ-nia commented on src/partials/program.html
> +        <ul>
В ТЗ было написано трехуровневый список. Ты сделал таблицей. Мне кажется была бы проще разметка (и как по тз) если:
`<ul>` и в ней 5 аналогичных лишек (расписую одну что б не слилось все) :
`<li-1>`
`<h3>`semester`</h3>`
`<ul>`
`<li-1-1>`
`<h4>`grammar`</h4>`
`<p>` nnnnn `</p>`
`</li>`
`<li-1-2>`
`<h4>`vocabulary`</h4>`
`<p> `lllllll `</p>`
`</li>`
`</ul>`
`</li>`
*цифры только для визуализации

2021-07-04 11:21 UTC, Vladosik12333 commented on src/partials/program.html
> +        <ul>
Читал ТЗ, но думал так удобней будет. Кинул вопрос в таблицу, если нельзя - изменю, если можно - напишу.

2021-07-04 20:09 UTC, OlenaZ-nia requested changes

2021-07-04 20:09 UTC, OlenaZ-nia commented on src/partials/program.html
> +                                Clauses: Conditional
Clauses: Conditional and Wishes - это я думаю одна лишка, т.к. and с маленькой буквы

2021-07-04 20:09 UTC, OlenaZ-nia commented on src/partials/program.html
> +                                Direct / Reported
Direct/Reported speech - одна лишка

2021-07-04 20:09 UTC, OlenaZ-nia commented on src/partials/program.html
> +                        <h4>Writing</h4>
Если это не из-за поломанного макета, в этом списке одна лишка - Formal Letter. Ну или просто р, как ты сделал ниже. Но вполне можно оставить списком из расчета на будущее, что могут добавится пункты.

2021-07-04 20:09 UTC, OlenaZ-nia commented on src/partials/program.html
> +                                Revision
у меня по макету этого пункта нет

2021-07-04 20:09 UTC, OlenaZ-nia commented on src/partials/program.html
> +                                Tests
этого пункта тоже нет

2021-07-04 20:09 UTC, OlenaZ-nia commented on src/partials/program.html
> +                <p>Revision Tests</p>
если в коде который выше решишь поставить `р`, то и здесь оставишь; если все таки список с одной лишкой (тип на будущее), то и здесь так само поменять.

2021-07-05 14:24 UTC, OlenaZ-nia approved these changes

2021-07-05 14:51 UTC, merged