feature/footer
AnnaYegorova/team-project-group-1 pull request #9
Opened 2021-07-04 07:24 UTC by dmistori84

Добавляет футер, но свг не отображается. При добавлении свг с телефоном, пропадает последний див, поэтому он закоментирован

2021-07-04 17:58 UTC, AnnaYegorova requested changes

2021-07-04 17:58 UTC, AnnaYegorova commented on src/partials/footer.html
> +            <a class="footer__tel" href="+38 (000) 000 00 00">
Дописать href="tel:+38   "

2021-07-04 17:58 UTC, AnnaYegorova commented on src/partials/footer.html
> +            <svg class="icon-insta" width="40px" height="40px">
Svg оберни в ссылку<a>

2021-07-04 17:58 UTC, AnnaYegorova commented on src/partials/footer.html
> +                <use href="../images/icons/instagram.svg"></use>
Путь к картинке в html прописываем через одну точку.

2021-07-04 17:58 UTC, AnnaYegorova commented on src/partials/footer.html
> +                @ All rights reserved, 2019
Спецсимвол заменяешь на &copy;

2021-07-05 18:42 UTC, Vladosik12333 reviewed
Не внесены правки описанные Анней выше.

2021-07-07 10:27 UTC, AnnaYegorova commented
1

2021-07-07 10:27 UTC, closed without merging

2021-07-07 10:27 UTC, AnnaYegorova commented
1111